import type { Metadata } from 'next'
import { GlobalProvider } from '~/context'
import { Providers } from '~/store/provider'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <GlobalProvider>
                    <Providers>{children}</Providers>
                </GlobalProvider>
            </body>
        </html>
    )
}
