'use client'
import type { Metadata } from 'next'
import { GlobalProvider } from '~/context'
import { Providers } from '~/store/provider'
import { Providers as ThemeProvider } from '~/theme/provider'
import { SnackbarProvider } from 'notistack'
import { SnackbarConfig } from '~/config'
import { Provider } from 'react-redux'
import { store } from '~/store'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <Provider store={store}>
                    <GlobalProvider>
                        <ThemeProvider>
                            <SnackbarProvider {...SnackbarConfig}>
                                <Providers>{children}</Providers>
                            </SnackbarProvider>
                        </ThemeProvider>
                    </GlobalProvider>
                </Provider>
            </body>
        </html>
    )
}
